#! /bin/bash


case "$1" in
  start)
    echo "Starting server"
    # Start the daemon 
    /usr/local/bin/jn_mailbox_daemon start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    /usr/local/bin/jn_mailbox_daemon stop
    ;;
  restart)
    echo "Restarting server"
    /usr/local/bin/jn_mailbox_daemon restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/testdaemon.sh {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

